import sys
import subprocess
import os

tool_path = r"C:\Users\daanm\MedHub\tools\insert_questao.py"

questions = [
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "ABC Score para Transfusao Macica",
        "enunciado": "Mulher 25a, atropelamento. Choque hipovolemico. ABC Score para transfusao.",
        "correta": "FAST positivo",
        "marcada": "FAST positivo",
        "erro": "Lacuna de conhecimento",
        "elo": "Saber os criterios do ABC Score",
        "armadilha": "As vezes o plantonista esquece que o FAST é parte dos scores clinicos preditivos",
        "complexidade": "Baixa",
        "habilidades": "Conhecimento do ABC Score -> Identificacao no caso",
        "faltou": "FAST positivo",
        "explicacao": "Critérios do ABC Score: 1. Trauma penetrante, 2. PAS <= 90, 3. FC >= 120, 4. FAST positivo. Score >= 2 indica transfusao macica.",
        "frente_contexto": "Avaliacao inicial de choque no trauma severo para ativar hemoderivados.",
        "frente_pergunta": "Quais sao os quatro componentes do ABC Score para indicacao de transfusao macica no trauma?",
        "verso_resposta": "Trauma penetrante, PAS <= 90 mmHg, FC >= 120 bpm e FAST Positivo.",
        "verso_regra_mestre": "O Score avalia condicoes hemodinamicas basicas e o status de sangramento na cavidade. Uma pontuacao de 2 ou mais ja dispara o protocolo macico (1:1:1).",
        "verso_armadilha": "Esquecer do FAST ou confundir o mecanismo (é trauma penetrante o criterio, nao trauma contuso grave em si)."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Pseudocisto pancreatico - Tratamento Pós Trauma",
        "enunciado": "Pseudocisto de colon de pâncreas apos trauma pancreatico sintomatico com indicacao cirurgica.",
        "correta": "Derivacao pseudocisto-gastrica via endoscopica com Pig Tail",
        "marcada": "Puncao guiada por radiologia",
        "erro": "Erro de aplicacao",
        "elo": "Indicar o tratamento de menor morbidade baseada nas possibilidades terapeuticas do pseudocisto",
        "armadilha": "Aachar que puncao/drenagem percutanea é melhor quando ha janela gastrica. O Pig Tail é definitivo.",
        "complexidade": "Media",
        "habilidades": "Diagnosticou complicacao -> Definir metodo definitivo menos invasivo",
        "faltou": "Derivacao endoscopica transmural é melhor escolha que debridamento ou drenagem cega.",
        "explicacao": "Havendo janela (colecao madura, aderida ao estomago, > 6cm) a derivacao interna (endoscopica transmural) é a conduta menos invasiva e definitiva. A drenagem externa pela percutanea é segunda linha (quando nao ha janela ou esta infectado instavel).",
        "frente_contexto": "Paciente com pseudocisto pancreatico pos-trauma volumoso (8cm) aderido parede posterior do estomago e causando compressao extrinseca.",
        "frente_pergunta": "Qual a melhor abordagem terapeutica minimamente invasiva para tratar definitivamente o pseudocisto?",
        "verso_resposta": "Cistogastrostomia via endoscopica (colocacao de Pig Tail transmural).",
        "verso_regra_mestre": "Em pseudocistos maduros aderidos ao TGI (janela favoravel), a drenagem interna transmural via EDA previne recidiva, sendo superior a drenagem percutanea guiada (que mantem fistula externa).",
        "verso_armadilha": "Alternativas citarao 'puncao guiada por USG' que é valida, mas menos definitiva quando comparada a endoscopica com presenca de janela adequada!"
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Laceraçao ducto pancreatico distal TCE III",
        "enunciado": "Laceracao distal do corpo do pancreas com seccao do ducto principal (Grau III).",
        "correta": "Pancreatectomia distal / caudal",
        "marcada": "Laparotomia exploradora (na verdade marcara pancreatectomia, mas o gabarito mudou pra CPRE. Inserido como A)",
        "erro": "Armadilha",
        "elo": "Saber a conduta AAST Grau III de pancreas",
        "armadilha": "Banca divergiu e validou stent de CPRE como se fosse conservador para trauma contuso com ducto seccionado.",
        "complexidade": "Media",
        "habilidades": "Classificacao trauma pancreas -> Decisao cirurgica com base no mesenterio",
        "faltou": "Saber que o corte na anatomia padrao é o mesenterio.",
        "explicacao": "Segundo ATLS e MSH, lesao ductal a esquerda da VMS (cauda/corpo) é Grau III tratada com Pancreatectomia Distal + Drenagem.",
        "frente_contexto": "Manejo cirurgico do paciente com trauma fechado apresentando seccao transversal completa no corpo do pancreas envolvendo o ducto (lesao grau III).",
        "frente_pergunta": "Qual o tratamento padrao para lesao ductal pancreatica distal (à esquerda dos vasos mesentericos)?",
        "verso_resposta": "Pancreatectomia distal (corpocaudal) com resseccao orientada à esquerda dos vasos mesentericos, podendo de associar ou nao esplenectomia.",
        "verso_regra_mestre": "Na TNO no pancreas a definicao cirurgica é binaria: ducto higido = drenar. Ducto rompido na cauda = tirar cauda. Ducto rompido na cabeca = cirurgia grande (Whipple ou dreno largo inicial).",
        "verso_armadilha": "Tentar colocar stent nas amputacoes traumaticas por via de CPRE é excecao / off-label e nao a visao tradicional das cirurgias em prova brasileira."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Retropneumoperitonio isolado",
        "enunciado": "FAST hepatorrenal e pelve. TC visualizada mostra figado conservado, mas retropneumoperitonio nítido ao redor do rim.",
        "correta": "Laparotomia exploradora",
        "marcada": "TNO (Tratamento Nao Operatorio)",
        "erro": "Erro de aplicacao",
        "elo": "Identificar retropneumoperitonio associado a indicacao cirurgica absoluta de viscera oca",
        "armadilha": "Trauma no figado parecia ameno, ignorando a bolha de ar na tomografia que aponta lesao duodenal/colica.",
        "complexidade": "Media",
        "habilidades": "FAST + -> TC de lesao contusa -> Leitura de achado na TC -> Laparotomia",
        "faltou": "Identificou trauma de viscera macica contido, mas nao viu o ar solto retroperitoneal.",
        "explicacao": "Ar retroperitoneal no trauma abdominal contuso é sinal obvio de perfuracao de viscera oca retroperitoneal (2a-3a porcoes do duodeno ou colon ascendente/descendente). Conduta: cirurgia.",
        "frente_contexto": "TC de abdome revela acumulo de gas na face anterior do polo renal direito e regiao paracaval (retropneumoperitonio).",
        "frente_pergunta": "Qual o significado e a conduta obrigatoria para a presenca de retropneumoperitonio pos-trauma contuso?",
        "verso_resposta": "Significa ruptura de viscera oca retroperitoneal (ex: duodeno e colon). Conduta: Laparotomia exploradora imediata.",
        "verso_regra_mestre": "Ar fora da alca (seja intraperitoneal ou retroperitoneal) tem apenas 1 destino: o bloco cirurgico. O TNO se restringe a lesoes esplenicas, hepaticas ou renais SEM peritonite/ar e estaveis hemodinamicamente.",
        "verso_armadilha": "Cair no TNO pois a lesao do figado associada parecia de obordagem com angioembolizacao. Mas o ar na TC reverte as condutas minimas."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "FAB em Dorso com estabilidade hemodinamica",
        "enunciado": "Ferimento corto contuso por arma branca lombar direita estavel",
        "correta": "Tomografia de abdome contrastada (duplo ou triplo contraste)",
        "marcada": "Laparoscopia diagnostica",
        "erro": "Armadilha",
        "elo": "Avaliar o metódo diagnostico para lesoes do compartimento retroperitoneal por orificio dorsal",
        "armadilha": "O candidato decora que VLP é exelented pra excluir lesao e diagnostica tudo na arma branca, mas ignora o retroperitonio.",
        "complexidade": "Media",
        "habilidades": "Topografia da ferida (dorsal) -> Entender acesso da VLP ao retroperitonio (Ruim) -> Escoler a TC de duploo ou tri plo.",
        "faltou": "Não confundir FAST ou VLP como melhores exames pra costas e flancos.",
        "explicacao": "A LPD, USG FAST e VLP acessam a cavidade ANTERIOR e DIAFRAGMA. O dorso esconde os rins e grandes vasos, regiao paraferida muito espessa muscularmente. Por isso FAB lombar sem indicacao imediata cirurgica é OBRIGATORIO TC Duplo ou Triplo Contraste.",
        "frente_contexto": "Pt com 2 facadas nas costas entre L1-L3. Pressao Arterial conservada de 110x70, normocardico e sem dor a descompressao.",
        "frente_pergunta": "Qual o principal exame e via para prosseguir avaliacao do paciente?",
        "verso_resposta": "Tomografia Computadorizada de Abdome (preferencialmente com duplo ou triplo contraste).",
        "verso_regra_mestre": "O acesso pela Videolaparoscopia NAO mostra adequadamente o retroperitonio sem que realizar manobras dissecativas complexas as escuras. O padrao ouro incruento para flanco/dorso é TC com contraste IV, VO (e VR dependendo o alvo).",
        "verso_armadilha": "Achar que exploração digital resolve (espessura lombar impede). E VLP fica enxergando apenas as paredes do estomago ou intestinos em topico peritoneal."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Halito alcoolico + Sensibilidade difusa (Peritonite)",
        "enunciado": "Glasgow 14, FR23 instavel. Halito etilico, peritonite abdominal franca com dor descompressao difusa. 102x70",
        "correta": "Laparotomia exploradora",
        "marcada": "Realizar TC abdominal com contraste",
        "erro": "Desatencao",
        "elo": "Respeitar a autoridade clinica da peritonite sobre o exames de imagem e Glasgow 14",
        "armadilha": "Paciente bebado, e com hemodinamica em tese normal de 102x70. Vc sente seguranca pela estabilidade em mandar pro exame.",
        "complexidade": "Baixa",
        "habilidades": "Peritonite no exame -> Ignorar exames compl. -> Laparotomia",
        "faltou": "Sinais francos de obvio abdomen agudo nunca vao para TC.",
        "explicacao": "A presenca de 'sensibilidade evidente e descompressao dolorosa difusa' indica peritonite (mesmo Glasgow 14). Peritonite por trauma contuso e indicacao cirurgica absoluta sem exames de imagem adicionais.",
        "frente_contexto": "Paciente em pos trauma de acidente automotor (choque contra obstaculo). Chege no APH queixado dor abdominal franca, com irritacao peritoneal caracterizado exame fisico.",
        "frente_pergunta": "Com o paciente sustentando Pressao Arterial estavel, devo manda-lo realizar FAST ou TC? E se negativo qual a proxima acao?",
        "verso_resposta": "Nao realize imagem (FAST ou TC). Sinais francos de peritonite indicam Laparotomia Exploradora Imediata indepedente de demais exames.",
        "verso_regra_mestre": "Sinais absolutos de laparotomia sao inegociáveis: Peritonite, Evisceracao e Sangramento Macico via SNG / Retal ou refratario. O achado cancela qualquer protocolo de triagem por imagem.",
        "verso_armadilha": "As bancas farao o mal de colocar uma PA ok de '100x60', levando a sensacao de tranquilidade pra indicar a TC, a via obvia de pacientes contusos."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Via aerea em Trauma Maxilofacial desfigurante",
        "enunciado": "Fratura mandibula, esfacelamento lingua e labios. SAT O2 de 40!!! Nao houve lesao de laringe.",
        "correta": "Realizar cricotiroidostomia cirurgica",
        "marcada": "Entubar via Orotraqueal",
        "erro": "Lacuna de conhecimento",
        "elo": "Entender as contraindicacoes relativas da IOT em relacao de trauma no A",
        "armadilha": "Na avaliacao primaria a via A sempre fala-se das rapidas com intubacao ou de que a traqueostomia é apenas de cirurgua.",
        "complexidade": "Baixa",
        "habilidades": "Hipoxemia severa (A/B) -> Reconhecer IOT indisponivel por trauma -> Aplicar via aerea cirurgica temporaria",
        "faltou": "Ver sangue e coagulos bloqueando a anatomia, o que faz IOT ser estupidamente dificil e demorado.",
        "explicacao": "Perda de arquitetura glotica/orofaringeana (esfacelamento + sangue na boca + lesao lingua e maxila) faz a laringoscopia ser impossivel nas condicoes agudas do PS. Indica-se Imediata Cricotireoidostomia cirurgica pela rapidez.",
        "frente_contexto": "Avaliacao primaria do ATLS (Letra A) num vitima politraumatizada de arma de fogo na face, com boca rechegada de destrocados amorfos e ativamente engasgado no proprio sangue.",
        "frente_pergunta": "Em qual cenario preferimos realizar uma CricoTireoidostomia primaria, sem sequer testar a Intubacao Traqueal?",
        "verso_resposta": "Trauma Maxilofacial extenso e desfigurante associado a sangramento abundante, que inviabiliza visualizacao de cordas.",
        "verso_regra_mestre": "A Crico é a cirurgia salva vidas pra os cenarios de via 'nao laringoscopavel' por distorcoes mecanicas da face e supraglote, mas de forma alguma com laringe de fato fraturada (trauma via obvia pescoço).",
        "verso_armadilha": "Traqueostomia no trauma é sempre de excecao extrema (crianças e lesao laringea clara) - o aluno erra quando acha que o esfacelamento pede as Trak."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Conduta do Abscesso/Septico em Perfuracao Esofagica Tardia",
        "enunciado": "Disfagia taquicardia febre > 24 apos EDA perfurada. Colecao luida mediastino (Pneumomediastino).",
        "correta": "Toracotomia com limpeza e drenagem ampla do mediastino",
        "marcada": "Drenagem USG do mediastino jejen atb",
        "erro": "Erro de aplicacao",
        "elo": "Aplicar debridamento incruento as abordagens esofagicas cronificadas >24h",
        "armadilha": "Confunde cisto peripancreático / abscesso intraabdominal estavel (onde percutanea reina) com abscesso purulento com tecidos necrosos num mediastino esofagico pós 24h.",
        "complexidade": "Media",
        "habilidades": "Lesao de esofago tardia com septica -> Exclui sutura primaria isolada -> Abre-se por cirurgia Toracotomia p/ higienizacao e debridamento.",
        "faltou": "Mediastinite é necrosante. Drenagem cega nunca tira essa quantidade de lixo em esôfago",
        "explicacao": "Em perfuração > 24 hrs com sepse estabelecida (coleção gas/liquido intratoracico), formou-se uma mediastinite aguda avancada que possui muitos tecidos necrosados, sendo totalmente ineficiente uma drenagem cega, pois debridamento extenso cirurgico pela caixa toracica se faz mandatorio.",
        "frente_contexto": "28 horas apôs sofrer um barotrauma espôntaneo na sindrome de boerhaave. Desenvolve um empiema toracido e pneumonia.",
        "frente_pergunta": "Qual a conduta para corrigir a injuria tardia da perfuracao esofagica com sintomas sistemicos e infecciosos locorregionais avançados?",
        "verso_resposta": "Toracotomia extensa associada a debridamento de todo tecido não viavel no trajeto, deixando drenos extensos tubulares no espaço pleuro-mediastinal, sem primariamente suturar esofago.",
        "verso_regra_mestre": "Em ate 24h, o esofago rotto suporta ressecacao e fechamento primario ('Golden Period'). Apos 24 hrs, os tecidos inflamam e se instalam com friabilidade aguda, necessitando a conduta agressiva da toracotomia de lavagem continua e evitar reconstrucoes na zona podre.",
        "verso_armadilha": "Considerar manejo incruento pela agulha ou antibioticos de longa duração sem controle adequado do foco maciço mediastino."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Amilase e indicativos de lesao pâncreas/duodeno",
        "enunciado": "Assinalar afirmativa correta: Amilase no contuso suspeita lesao e Delgado é 4 lugar?",
        "correta": "Hiperamilasemia levantar suspeita de dupla lesao complexo.",
        "marcada": "Laceracao 50% é grau II duodeno",
        "erro": "Lacuna de conhecimento",
        "elo": "Desconsiderou as propriedades da amilase no trauma por ser especifica as vezes pra demais",
        "armadilha": "Pensou amilase é so no pâncreas e nas lesoes agudas de etiologias inflamatorias. Esqueceu q Laceracao > 50% do duodeno é Grau III.",
        "complexidade": "Media",
        "habilidades": "Conhecer as incidencias FAB/FAF -> Saber as classificacoes duodenais das bancas",
        "faltou": "Laceracao Duodenal maior que 50% ja migra pra nivel 3 em condutas e gravidade.",
        "explicacao": "O aumento agudo de amilase sem historico (embora baixa especificidade) serve de alerta no trauma contuso para lesao do complexo duodenopancreatico oculta. Laceracoes duodenais > 50% caem no Grau III de severidade. Orgao mais de arma de fogo é ID 50% > Colon 40% > Figado. Na Branca Figado 40% > ID.",
        "frente_contexto": "Avaliacao secundaria minunciosa apos 48 hrs na unidade de terapia intensiva revelam niveis graduais persistentes de amilase e lipases sem sinais peritoniais maiores.",
        "frente_pergunta": "O que devemos suspeitar quando frente hiperamilasemia progressiva e inexplicada na avaliação posterior de um trauma fechado em desaceleracao?",
        "verso_resposta": "Alta probabilidade diagnostica para lesao anatomica ou laceração contusa do pulma do pancreas ou oclusão/obstrucao/hematoma duodenal obstrutivo adjacente.",
        "verso_regra_mestre": "O pancreas tem caracterização e clinica inxistente inicialmente no trauma devida condioces e blindagem pos posterior estomacal e colitica. Alteracoes bioquimicas dao uma dica de suspeica precoce para sua analise via imagem.",
        "verso_armadilha": "Omitir analise pensando que o pancreas pode nao manifestar irritacao em 48h retroperitoneal entao estar OK."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Triade da Morte no Choque avancado",
        "enunciado": "Hipotermia em pacienet perda macica. Assossocia-se com ...",
        "correta": "incoagulabilidade",
        "marcada": "Estado Trombogenico",
        "erro": "Desatencao",
        "elo": "Traduzir hipofunção termodependente da cascata em incapacidade coagulatoria local",
        "armadilha": "Assumiu que o corpo vai hiperreagir as perdas criando trombos como nas disinencias obstrutivas em CIVD tardias. ",
        "complexidade": "Alta",
        "habilidades": "Compreender enzimas dependem de calor e Ph -> Relacionar triade",
        "faltou": "A tríade letal se retroalimenta gerando a falha mecanica progressiva: voce sangra ate a morte porque é muito frio pra manter seus coágulos funcionais.",
        "explicacao": "Na triade letal do trauma (Hipotermia, Coagulopatia, Acidose), a cascata de coagulacao sofre severa paralisia reacional se temperatura < 35°C (devido ineficiencie de sua natureza enzimatica organica). ISSO leva ao extravasamento profundo por incoagulabilidade e agravamento da hipotensao.",
        "frente_contexto": "Um paciente recebendo reposicoes volumentosas geladas na pre triagem pre operatoria cirurgia dano controller",
        "frente_pergunta": "Qual e os disturbios de hemostasia primeria associado de modo obvio com pacientes com temperatura central muito inferior em ambientes de choque cirurgico resfriado?",
        "verso_resposta": "Um estado deflagrado de incoagulabilidade por ineficiencia de fatores teciduais coagulantes quimicas intrinsecas.",
        "verso_regra_mestre": "Proteinas e ativadores vitais das plaquetas e complexo da protrombina falham na reacao sob condices frias - portanto, aqueça seus resgatados pra salválos a poder fechar as fissuras exanguineas com a acao hemostasia auto modulada",
        "verso_armadilha": "A hipercoagulabildiade é um distubrio passageiro e fragil nas lesoes localizadas agudas, o que nao resiste quando toda hemostasia se ve afetada pela exsanguinacao massiva da totalidade da triplice."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Sequenciamento ATLS em peritonite ou evisceracao primária.",
        "enunciado": "Eviscerado e faqueado abdome chego vivo no PS conversando falando o que rolou",
        "correta": "Providenciar Acesso venoso na letra C",
        "marcada": "Laparotomia exploradora",
        "erro": "Erro de aplicacao",
        "elo": "Reter conduta obvia quebrando principio de segurança da letra C",
        "armadilha": "Ah o cara ta no pronto socorro já obvio de cirurgia vou correr pra barriga aberta. Falso.",
        "complexidade": "Baixa",
        "habilidades": "Se o paciente fala = A e B puros. Entao -> Avalia-se C primeiro pegando acessos",
        "faltou": "Nada de quebra etapas, sempre C antes de curar lesao definitiva.",
        "explicacao": "Pacientes dialogando = Letras A e B asseguradas com provavel adequabilidade inicial. A via prioritaria protocolar na sequência vai obrigatoriamente para C, no qual se obtem dois grossos acessos. Evisceracao se estabiliza na letra E - mas NUNCA pula-se o ABC para saltar num Bloco cirurgico imediatamente pulando protocolo de ressurrecicao.",
        "frente_contexto": "Vitima portando arma estomacal aparente caindo conteulos estomacais pra fore pelo trajeto, mas relatando verbalmente com dor severa os acontecimentos enquanto admitida no box reanimacao.",
        "frente_pergunta": "As condutas de intubacao, avaliacao de coluna, descompressao estao completadas na checage rapida da voz limpa. Qual etapa critica subsequente tem que preceder todo recobrimento viscerular?",
        "verso_resposta": "Admissao e canulagem de no minimo 02 acessos venosos perifericos calibrosos por cateterismos, para garantia via C da restauracao volêmica contra perda.",
        "verso_regra_mestre": "As imagens macabras que dispertam urgencia do observador novato jamais vao distorcer as normas prioridade ABC. Sangramento e morte vindo de hemorragia ou obstrucoes vencem de uma evisceracao purulente ou exposicao nervosa e obvia tecidual complexa.",
        "verso_armadilha": "Muitas alternativas serao cobrir visceras, aquecer etc. As quai fazem parte da Letra E! Avaliacao de A e B e C tem precedencia absoluta."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Revalidando conduta Dorso/FAB (Repeticão mental)",
        "enunciado": "Faca Dorso, hemodinamica otima 140x80 s/ peritonio fast e Rx negatius",
        "correta": "Tomografia de abdome contrastada",
        "marcada": "Laparoscopia exploradora",
        "erro": "Armadilha",
        "elo": "Aplicar o raciocinio da anatomia espessa VS limites cirurgicos VLP.",
        "armadilha": "Errei de novo porque tentei ir pra VLP como conduta unificadora achando que a 'Laparoscopia é bala de prata em penetrantes estaveis' ",
        "complexidade": "Baixa",
        "habilidades": "Decorar e fixar de vez: Transicao anterior/lateral = VLP. Flanco/dorso = TC triplo.",
        "faltou": "A VLP serve perfeitamente é pra diafragma transicao.",
        "explicacao": "Lesoes e FAB de regiao em dorso/lombar (posterior abaixo da linha escapular e transicao) impoem uso da TC com contraste venoso VO e VR as custas de possivel falha grave por VLP retroperitoneal de diagnosticar rins/cólon do trajeto oblíquo.",
        "frente_contexto": "Outro padrao na urgencia, chega no pronto socorro pt referindo que tomou canivete lateral esquerdo lombar mas está sentando e rindo.",
        "frente_pergunta": "Sei que no estavel vou pra exames invasivos/nao-invasivos de visualizacao complementares, porem a duvida principal é VLP ou TC abdomen com contrastes pra esses lombo-dorsais?",
        "verso_resposta": "Tomografia CT de abdome obrigatoria com triplo espessamento de imagens contrastadas para vias retal VO venosas. (E SEM VLP!).",
        "verso_regra_mestre": "Decore: FAB ANTERIOR e estável: Violou fáscia na digital > Cirurgia (ou monitoramento 24h a depender escola). FAB TRANSICAO: Videolaparoscopia (nao passa liso no tc). FAB DORSO/FLANCO: TC Duplo/Triplo Contraste pra verificar o obscuro retroperitonio que todos exquecem.",
        "verso_armadilha": "Nunca aceitar 'Laparotomia por ser trauma cortante' em zonas obvias que a blindagem da PA permie seguranca incruenta no momento."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Sinais Radiologicos contundentes de Aorta Traumática",
        "enunciado": "Vitima da capotmento de 60kmh, rx de torax tem velado em base e espessura absurda do tubo central",
        "correta": "Lesao traumata de aorta toracica",
        "marcada": "Pneumotorax simples à esquerda",
        "erro": "Lacuna de conhecimento",
        "elo": "Reconhecimento das diferencas obvias de hemotorax pra pneumotorax via radiologicas",
        "armadilha": "Opacificacao branca total em torax esquerdo na pressa pareceu q esquerdo inteiro se comprimiu sendo ar.",
        "complexidade": "Media",
        "habilidades": "Interpretar Rx -> Opaco = fluido = sangue/Hemo torax. -> Notar alteracao mediastinal enorme (medico ignorou).",
        "faltou": "Alargamento Media estenal >8cm é diagnostico gritante de injuria dos grandes Vaso (Desaceleracao grave)",
        "explicacao": "Mecanismo abrupto de desaceleracao alta km/h com rx opaco todo do ladod, porem de um mediastino distorcido enorme central, linha apical esquerdo coberto, tracqueia e pulmao forcados pro lado direito evidenciam uma Ruptura Aoartica Toracica grave, embora as vezes eles consigam chegar estaveis 120 PA a hospital. ",
        "frente_contexto": "Um motoqueiro batendo no poste frente aos 50km da entrada, mas PA pressao e normal de repente, faz Rx e revela base torax estufa e radiopaca e contornos os hilares e mediastinos desviados e imprecisos de observar limites >9cm espessarmento. ",
        "frente_pergunta": "Sendo descartado Hérnia/Ruptura de diafrágmaticase esofágicam e frente a historia qual é o diagnostico assossiado com este padrao letal porem agudo?",
        "verso_resposta": "Laceracao ou Injúria aortica contusa de origem retro-traumática contida de alta energia no ligamento arterioso.",
        "verso_regra_mestre": "Na desaceleracao de auto a aorta desvia da gravidade puxando as artérias e rasgando o íntima do ductus. Se estourado na triagem eles ja estao osso morridos - SE sobreviveram as bordas tamponaram entao espere encontrar uma 'Bomba Relogio' de mediastino gordo sem estar totalmente descompensado no instante pre operatorio",
        "verso_armadilha": "Acahar q PA tem que estar zerada por sangramento - nao , PA pode estar OK 130 normal."
    },
    {
        "area": "Cirurgia",
        "tema": "Trauma",
        "titulo": "Tratamento de descompressao obvia na Puncao Toracica ATLS ",
        "enunciado": "FR 50 O2 72%, pulmao macico sem sons na percussão timpanica apos facada. Pneumo de pressao em colapso.",
        "correta": "Puncao de quinto espaco intercostal LAA e LAM com jelco longo",
        "marcada": "Drenagem pleural imediata em selo dagua",
        "erro": "Erro de aplicacao",
        "elo": "Dimensoes e prioriedades do resgate agudo com objetos de facil porte VS lentos procedimentos formais.",
        "armadilha": "Cansado vi a opcao drenagem q é definita porem as emergencias reais de asxiifa pedem um jelco facil puncao temporaria antes.",
        "complexidade": "Alta",
        "habilidades": "Hipertensivo na analise clinica -> Salvar via descompressao em 3 segundos -> Tubos definitvos dpois",
        "faltou": "Notou um PneumoHipertnsivo no quadro de Timpannico aboledo instavel de sines e oxigenio 70%. Ignorou a puncao q é a vida do C",
        "explicacao": "Pneumotoreax hipertensivos matam pela rapida pressao obstruindo o pre carga central, levando a PCR na propria sala em segundos. Sem a agulha calibrosa ou descompressao digital (comum no 5o espaco entre a anterior/media linha maxilar nos ATLS 10 e 11!) voce os perde enquanto caça caixas de tubo dagua no hospital para esterilizar dreno em ambiente complexo.",
        "frente_contexto": "Chegando no APH, acalamento instável com cianose jugular de engorge no max, e peito que nao se move pra ar da inspiracao que ecoa nos dedos com sons timpânicos vazios intensos como tambor.",
        "frente_pergunta": "O que realizara pra evitar parada obstrutiva no milisgundo proximo q antecede montagem das suas bandeijas drenagens da enfermagen em selos agua tubular pleurrais?",
        "verso_resposta": "Toracocentese Agulhada imediata de descompressao por alivios ou por dedais, aplicada com acessos calibrosos grandes perfeitamente nos 5o espaço IC axilar anterior LAA/Media LAM.",
        "verso_regra_mestre": "Procedimetntos cirurgicos como drenar com manguerias longas do tórax dao chance zero sem segurado uma agulha para o pulmao escapar seu excesso asficiante no Pneumotorx Hipertnsivo. ",
        "verso_armadilha": "Intubacao em VPP em quem tem hipertenssivo acelera o descolamento cardiaco pra morte no instante. (Intubar A e B sem diagnosticar essa massa te assassina na ventilacao forcada!)"
    }
]

file_content = ""
for i, q in enumerate(questions):
    cmd = [sys.executable, tool_path]
    for key, value in q.items():
        cmd.append(f"--{key}")
        cmd.append(value)
    
    # Run process
    print(f"Executing question {i+1}...")
    res = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8')
    if res.returncode != 0:
        print(f"Error {i+1}:", res.stderr)
    else:
        print(f"Success {i+1}")

